apiVersion: v1
kind: Pod
metadata:
  name: news-db
  labels:
    app: news-db
spec:
  containers:
    - name: db-news-container
      image: aluracursos/mysql-db:1
      ports:
        - containerPort: 80
      # Declaração das variáveis utilizando a estrutura do ConfigMap (get env from configmap)
      envFrom:
        - configMapRef:
            name: db-configmap

      # Declaração das variáveis utilizando a estrutura do ConfigMap (by key ref)
      # env:
      #   - name: MYSQL_ROOT_PASSWORD
      #     valueFrom:
      #       configMapKeyRef:
      #         name: db-configmap
      #         key: MYSQL_ROOT_PASSWORD
      #   - name: MYSQL_DATABASE
      #     valueFrom:
      #       configMapKeyRef:
      #         name: db-configmap
      #         key: MYSQL_DATABASE

      # Declaração das variáveis utilizando a estrutura do env do container
      # env:
      #   - name: "MYSQL_ROOT_PASSWORD"
      #     value: "q1w2e3r4"
      #   - name: "MYSQL_DATABASE"
      #     value: "empresa"
      #   - name: "MYSQL_PASSWORD"
      #     value: "q1w2e3r4"
