apiVersion: v1
kind: Pod
metadata:
  name: pod-volume
spec:
  containers:
    - name: nginx-container
      image: nginx:latest
      volumeMounts:
        - mountPath: /first-volume
          name: first-volume
    - name: jenkins-container
      image: jenkins/jenkins:alpine
      volumeMounts:
        - mountPath: /first-volume
          name: first-volume
  volumes:
    - name: first-volume
      hostPath:
        # C:\Users\mbrug\Desktop\first-volume - Usando WSL2
        path: /run/desktop/mnt/host/c/users/mbrug/desktop/first-volume
        type: Directory