version: '2'
services:
  zookeeper:
    image: docker.io/bitnami/zookeeper:3.8
    container_name: zookeeper-container
    hostname: zookeeper
    networks: 
      - broker-kafka
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ALLOW_ANONYMOUS_LOGIN: true
    volumes:
      - /home/mbrugnar/workspace/data-engineering-studies/apache-kafka/zookeeper-data:/bitnami
    ports:
      - 2181:2181
      
  kafka:
    image: docker.io/bitnami/kafka:3.2
    container_name: broker-kafka-container
    hostname: kafka
    networks: 
      - broker-kafka
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      ALLOW_PLAINTEXT_LISTENER: true
    volumes:
      - /home/mbrugnar/workspace/data-engineering-studies/apache-kafka/kafka-data:/bitnami
      
  kafdrop:
    image: obsidiandynamics/kafdrop:latest
    container_name: kafdrop-container
    hostname: kafdrop
    networks: 
      - broker-kafka
    depends_on:
      - kafka
    ports:
      - 19000:9000
    environment:
      KAFKA_BROKERCONNECT: kafka:9092

networks: 
  broker-kafka:
    name: broker-kafka
    driver: bridge  