apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: rs-news-system
spec:
  template:
    metadata:
      name: news-system
      labels:
        app: news-system
    spec:
      containers:
        - name: news-system-container
          image: aluracursos/sistema-noticias:1
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: system-configmap
  replicas: 1
  selector:
    matchLabels:
      app: news-system
